Mobile app/features01/fetch received hardcoded json
matt-kubica/weather-station pull request #9
Opened 2021-11-14 20:20 UTC by JoannaHankus

2021-11-14 22:48 UTC, xMacKow approved these changes

2021-11-15 15:03 UTC, matt-kubica requested changes

2021-11-15 15:03 UTC, matt-kubica commented on mobile/App.jsx
> +            isLoading: false,
Consider introducing set of states, as an enum. Right now state `isLoading == true` relate to the state when an app is actually fetching data (loading), but also to the state in which data is fetched. In case when data will fail to be fetched for some reason, app will remain in loading state and user won't be notified if something went wrong (despite logging to console, which is not visible for end user).

2021-11-15 15:03 UTC, matt-kubica commented on mobile/src/ExemplaryComponent.jsx
>  export const ExemplaryComponent = ({text}) => {
minor: I think we don't need this anymore so it can be deleted.

2021-11-15 15:03 UTC, matt-kubica commented on mobile/App.jsx
> +        let examples = this.getArticles();
minor: I think that assignment to variable is not necessary here?

2021-11-20 23:50 UTC, JoannaHankus commented on mobile/App.jsx
> +        let examples = this.getArticles();
I cant stop wondering, why are we writing in English?

2021-12-13 21:27 UTC, matt-kubica approved these changes

2021-12-13 21:28 UTC, merged